server:
  port: 8761
spring:
  application:
    name: cloud-dream-eureka-server-a
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: SUPERUSER

#eureka:
#  instance:
#    hostname: cloud-dream-eureka-server-a
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
##      defaultZone: http://admin:admin@cloud-dream-eureka-server-b:8762/eureka/,http://admin:admin@cloud-dream-eureka-server-c:8763/eureka/
#      defaultZone: http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/
eureka:
  instance:
    hostname: cloud-dream-eureka-server-a
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/,http://admin:admin@localhost:8763/eureka/
            defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/
#      defaultZone: http://192.168.241.152:8762/eureka/,http://192.168.241.153:8763/eureka/