server:
  port: 9411

# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: cloud-dream-zipkin-server
  main:
    allow-bean-definition-overriding: true
  # 配置mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.241.151:8666/TESTDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: 123456
      initial-size: 20
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
        resetEnable: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/

eureka:
  instance:
    hostname: cloud-dream-zipkin-server
#    preferIpAddress: true
  client:
    serviceUrl:
      #      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/,http://admin:admin@localhost:8763/eureka/
      defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/
#      defaultZone: http://192.168.241.151:8761/eureka/,http://192.168.241.152:8762/eureka/,http://192.168.241.153:8763/eureka/


#指明使用mysql存储
zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: 192.168.241.153 #localhost
#      username: lbl
#      password: 123456

management:
  metrics:
    web:
      server:
        auto-time-requests: false