server:
  port: 8095

spring:
  application:
    name: cloud-dream-gateway
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    druid:
#      url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#      username: root
#      password: 123456
#      initial-size: 20
#      max-active: 100
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: false
#        resetEnable: false
#        url-pattern: /druid/*
#        login-username: admin
#        login-password: admin
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
  zipkin:
#    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
    sender:
      type: rabbit
    rabbitmq:
      host: localhost
      port: 5672
#      username: lbl
#      password: 123456
      listener: # 这里配置了重试策略
        direct:
          retry:
            enabled: true
        simple:
          retry:
            enabled: true
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.cloud.dream.clouddreamgateway.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 0
#    #自定义填充策略接口实现
##    meta-object-handler: com.miaolicai.api.common.utils.MyMetaObjectHandler
#    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true
#
#
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: countSql

logging:
  level:
     com.cloud.dream.gateway: debug

feign:
  hystrix:
    enabled: true #开启feign hystrix 断路器功能

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8016/oauth/token
#      user-authorization-uri: http://localhost:8016/oauth/authorize
#      client-id: web
#    resource:
#      user-info-uri:  http://localhost:8016/api/member
#      prefer-token-info: false