server:
  port: 8764

spring:
  application:
    name: cloud-dream-hystrix-turbine

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/

eureka:
  instance:
    hostname: cloud-dream-hystrix-turbine
#    preferIpAddress: true
  client:
    serviceUrl:
      #      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/,http://admin:admin@localhost:8763/eureka/
            defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/,http://cloud-dream-eureka-server-c:8763/eureka/
#      defaultZone: http://192.168.241.151:8761/eureka/,http://192.168.241.152:8762/eureka/,http://192.168.241.153:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  app-config: cloud-dream-server-user,cloud-dream-server-version
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream