spring:
  redisson:
    address: "redis://10.0.131.236:6379"
#      password: 123456
  redis:
#      database: 0
#      host: 10.0.131.236
#      port: 6379
#      password:  123456    # 密码（默认为空） 这是中文
#      timeout: 6000      # 连接超时时长（毫秒）
      prekey: dev_       # redis 环境剥离，前置key test_:测试, dev_:开发, 正是环境:prod_, 默认是def_
      timeout: 0
      commandTimeout: 5000
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
      cluster:
        nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384