server:
  port: 8763
spring:
  application:
    name: cloud-dream-eureka-server-c
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: SUPERUSER
eureka:
  instance:
    hostname: cloud-dream-eureka-server-c
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
#      defaultZone: http://admin:admin@cloud-dream-eureka-server-a:8761/eureka/,http://admin:admin@cloud-dream-eureka-server-b:8762/eureka/
      defaultZone: http://cloud-dream-eureka-server-a:8761/eureka/,http://cloud-dream-eureka-server-b:8762/eureka/
